// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdWO7n3Bj9BtDYTJrB7Y2Wqcvh-D-RAMw',
    appId: '1:297485023175:web:a294f6da62cb0854bf0be2',
    messagingSenderId: '297485023175',
    projectId: 'mybook-deb9f',
    authDomain: 'mybook-deb9f.firebaseapp.com',
    storageBucket: 'mybook-deb9f.firebasestorage.app',
    measurementId: 'G-2R6Z0BRBJQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPpdKXF3A0_qs9YrrU3EdFwBIQxnojmYo',
    appId: '1:297485023175:android:b5d3b113464527bcbf0be2',
    messagingSenderId: '297485023175',
    projectId: 'mybook-deb9f',
    storageBucket: 'mybook-deb9f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD06mAWNv-LRVPOEgfDR5ix7BbdNSF69G0',
    appId: '1:297485023175:ios:053c6fd6c298b311bf0be2',
    messagingSenderId: '297485023175',
    projectId: 'mybook-deb9f',
    storageBucket: 'mybook-deb9f.firebasestorage.app',
    iosClientId: '297485023175-8cc1i93qefihuessbnqq577umrt97gdq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD06mAWNv-LRVPOEgfDR5ix7BbdNSF69G0',
    appId: '1:297485023175:ios:053c6fd6c298b311bf0be2',
    messagingSenderId: '297485023175',
    projectId: 'mybook-deb9f',
    storageBucket: 'mybook-deb9f.firebasestorage.app',
    iosClientId: '297485023175-8cc1i93qefihuessbnqq577umrt97gdq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdWO7n3Bj9BtDYTJrB7Y2Wqcvh-D-RAMw',
    appId: '1:297485023175:web:04f7f23dfe524aadbf0be2',
    messagingSenderId: '297485023175',
    projectId: 'mybook-deb9f',
    authDomain: 'mybook-deb9f.firebaseapp.com',
    storageBucket: 'mybook-deb9f.firebasestorage.app',
    measurementId: 'G-9KWBWK0E19',
  );
}
